### ISSUE TITLE
Where is php:5.5-cli?

### ISSUE THREAD

**Issue by deezone** [DoSomething/mb-docker#1]
I can't seem to find the base image `php:5.5-cli` on hub.docker.com. Where is the image coming from?

**Comment by sergiitk** [comment]
Hub: https://hub.docker.com/_/php/
Dockerfile: https://github.com/docker-library/php/blob/8943e1e6a930768994fbc29f4df89d0a3fd65e12/5.5/Dockerfile

For now I decide to go with 5.5 because that's what we have on the `mbc-php` server.
If this works fine, I'll upgrade it to latest 7.x.

**Comment by sheyd** [comment]
Just a thought, it might be worth it to upgrade to 7.x now, since you'll
get a really good performance boost.

**Comment by sergiitk** [comment]
Totally agree! Just want to make it work in known-to-work environment, then tweak it.

**Comment by deezone** [comment]
Ah, now I understand. Our current server: `mbc-php` runs Ubuntu. I just discovered Ubuntu is a Debian distro :hushed: 

Based on the (5.5/Dockerfile)

```
FROM debian:jessie
```

Now I understand your choice.

In terms of `5.5` vs `7.0`. Using `5.5` initially with clear intention of moving to `7.0` sounds great.

**Comment by deezone** [comment]
Should I move these details to the `README` as a PR or the repo wiki?

**Comment by sergiitk** [comment]
Yes, thanks! Sounds great!
