### ISSUE TITLE
Remove "c" in "mbc"

### ISSUE THREAD

**Issue by deezone** [DoSomething/mb-docker#2]
The naming convention be "mb" rather than "mbc" as the "c" stands for consumer. There are often "mbp" named application for producers. To make it clear that this image is for both producers and consumers use the "mb" name in paths and files.
- `mb-docker/mbc/` should be mb-docker/mb/`

**Comment by sergiitk** [comment]
Actually, I intended to use this Docker base image only for consumers.
I don't know what additional functionality would producers require.
The idea was to dockerize a producer and see if it needs anything else, then either combine consumer and producer Dockerfiles to one, or move what they share to the third file and base consumers and producers on it.

Sounds OK @DeeZone?

**Comment by deezone** [comment]
I think there's not a consistent difference between producer and consumer applications within the Message Broker system to justify having separate images. That being said, I don't think there's any harm in creating them but I suspect they'll end being identical.

I like your plan:

> The idea was to dockerize a producer and see if it needs anything else, then either combine 
> consumer and producer Dockerfiles to one, or move what they share to the third file and 
> base consumers and producers on it.

**Comment by deezone** [comment]
Glad we documented this, feel free to close :+1:
