### ISSUE TITLE
Add php5-curl library

### ISSUE THREAD

**Issue by deezone** [DoSomething/mb-docker#3]
Almost all of the Message Broker application (producers and consumers) need the `php5-curl` library. Add it to the `php-ext`s for the contain:

```
&& docker-php-ext-install mbstring bcmath zip php5-curl \
```

**Comment by sergiitk** [comment]
Yes, will do that.
Though, as I understand, it should be installed with apt-get, not `docker-php-ext-install`.

**Comment by deezone** [comment]
Your call, `apt-get` via `docker-php-ext-install`. How do you know which one to use?

Also, looking at php-5.5 DockerFile: https://github.com/docker-library/php/blob/8943e1e6a930768994fbc29f4df89d0a3fd65e12/5.5/Dockerfile I noticed that cURL might already be a part of the base image: https://github.com/docker-library/php/blob/8943e1e6a930768994fbc29f4df89d0a3fd65e12/5.5/Dockerfile#L52

Thoughts?

**Comment by sergiitk** [comment]
It might. I'll just make sure it's in `phpinfo()`.

**Comment by sergiitk** [comment]
It looks like cURL is supported by default:

```
❯ dk run -v $HOME/Development/mb/mb-secure-config/docker-dev/mb-secure-config.inc:/usr/src/mb/messagebroker-config/mb-secure-config.inc:ro --rm dosomething/mbc-transactional-email:latest php -i | grep -i curl
Configure Command =>  './configure'  '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--disable-cgi' '--enable-mysqlnd' '--with-curl' '--with-openssl' '--with-readline' '--with-recode' '--with-zlib'
curl
cURL support => enabled
cURL Information => 7.38.0
```
