### ISSUE TITLE
Why /usr/src/mb?

### ISSUE THREAD

**Issue by deezone** [DoSomething/mb-docker#4]
I don't have the answer, just asking. Why `/usr/src/mb` rather than `/usr/local/mb` or even `/opt`? 

```
mkdir /usr/src/mb
```

https://github.com/DoSomething/mb-docker/blob/master/mbc/Dockerfile#L13

**Reference**
- What is the difference between /opt and /usr/local? 
  http://unix.stackexchange.com/a/11552

**Comment by sergiitk** [comment]
I think I got the idea from [here](https://hub.docker.com/_/rails/) thought it's common for all docker containers. Let me check how other official containers do.

**Comment by sergiitk** [comment]
Looks like [Java](https://hub.docker.com/_/java/) container suggest the same approach:

```
COPY . /usr/src/myapp
```

**Comment by sergiitk** [comment]
And [python](https://hub.docker.com/_/python/):

> These images include multiple ONBUILD triggers, which should be all you need to bootstrap most applications. The build will COPY a requirements.txt file, RUN pip install on said file, and then copy the current directory into /usr/src/app.

**Comment by sergiitk** [comment]
And [php](https://hub.docker.com/_/php/):

```
COPY . /usr/src/myapp
```

I think now we can close this one.
